kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hello-world
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello-world
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hello-world
        version: v1
    spec:
      containers:
        - name: hello-world
          imagePullPolicy: IfNotPresent
          image: vibhorem/flask-hello-world-app:0.1.0
          ports:
            - protocol: TCP
              name: pythonport
              containerPort: 4000
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 150m
              memory: 400Mi
          livenessProbe:
            initialDelaySeconds: 25
            periodSeconds: 5
            tcpSocket:
              port: pythonport
          readinessProbe:
            httpGet:
              path: "/"
              port: pythonport
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            initialDelaySeconds: 30
            failureThreshold: 2
#      nodeSelector:
#        name: demo-node
      terminationGracePeriodSeconds: 10
